### ISSUE TITLE
Problem while assigning KONI port to WINDOWS

### ISSUE THREAD

**Issue by Dabuss** [SalvoVirga/iiwa_stack#59] opened 2017-03-01 17:49 UTC
Hello! 

I have troubles following the procedure detailed in [cabinet_setup](https://github.com/SalvoVirga/iiwa_stack/wiki/cabinet_setup). I'm trying to setup your solution on KUKA Sunrise.OS 1.7.1.12.

During Step 2:
> 2. Shutdown KRC
> It is the green icon in the system tray.

The green icon you describe seems to be the StartKRC Icon. Right-clicking on it displays "KRCDiag" or "Stop KRC". However, "Stop KRC" just shuts down the robot computer and disables the remote connexion as well, which prevents from doing any further action.
Hence, my solution was to go in the task manager and end StartKRC.exe. 

> 3. Open a terminal and type
> C:\KUKA\Hardware\Manager\KUKAHardwareManager.exe -assign OptionNIC -os WIN
> This will assign the KONI interface to Windows.

Running this command led to the following output in the KUKA Hardware Manager :

> 2017-03-01 16:23:29 INFO  Trying to assign OptionNIC to WIN ...
> 2017-03-01 16:23:30 INFO  Success running 'DevInstXP /Q /+ /ZI'
> 2017-03-01 16:23:30 INFO  BoardID from Registry: D3236-K1
> 2017-03-01 16:23:30 INFO  BusType OptionNIC found (HardwareID PCI\VEN_8086&DEV_1533&SUBSYS_11FC1734&REV_03, Address 0)
> 2017-03-01 16:23:30 WARN  Assignment not possible while KS is running

any attempts at killing more processes (KUKAHardwareService.exe, KukaPMService.exe KUKAHardwareManager) before step 3 didn't improve the last WARN message...

After hoping against hope that I was supposed to get this output, I tried the forth step. However, no reference to a KONI port seems to have added to the list of my Device Manager..

I believe I couldn't shutdown KRC properly (step 2) which prevented me from going any further. Would you have any solution to my problem please?

**Comment by mbanerj** [comment] 2017-03-01 18:53
StartKRC seems manages some kind of virtual network that enables the remote connection. Connect a monitor, mouse and keyboard to the cabinet, reboot, and try the steps again directly from the embedded Windows interface.

**Comment by Dabuss** [comment] 2017-03-02 08:41
@mbanerj 👍 Thanks a lot, it works ! 

I never realised Windows stayed alive after stopping KRC, although it makes sense now.

**Comment by mbanerj** [comment] 2017-03-02 12:49
Yeah, there's a lot of complexity going on inside the workings of the cabinet... glad you got it working!

**Comment by SalvoVirga** [comment] 2017-03-04 00:28
Yep, @mbanerj explained it correctly, thanks a lot :)

@Dabuss, you could close the issue if the problem is solved, else let me know!

**Closed** 2017-03-06 16:35 UTC
